### ISSUE TITLE
Tracking notifications

### ISSUE THREAD

**Issue by susheelvar** [samagra-comms/uci-apis#105]
**Goal** : Identify district-wise split of users who are:
- Sent notifications
- Receive notifications
- Interact with bot
- Complete interaction with bot

**Acceptance Criteria**
- Telemetry data from NL with mentor ID to be extracted
- Mapped with Mentor ID data from NL backend
- Table with required data points to be added to NL database for tracking & visualisation (data points reqd. to be added @susheelvar )

- [ ] **Step 1** : Identify users who are sent notifications 
- Pankaj shared a list of users who were sent notifications with phone number (in .log file) 
- To be converted and made to CSV by Susheel

- [ ] **Step 2** : Identify of the users sent notifications who all have received it via telemetry
- @karn need your help to export the Posthog logs via API
- @karn need your help to get the FusionAuth token mapping so that I can extract phone number/mentor ID 
- List of events for which data is required: 

1. nl-chatbotscreen-notification-received
2. nl-chatbotscreen-notification-opened 
3. nl-chatbotscreen-chatbot_media_accessed
4. nl-chatbotscreen-chatbot_media_downloaded

- Yuvraj to create API for both & also create DAG to automate this process

- [ ] **Step 3** : Join NL mentor table using mentorid/phone number to data dumps from steps 1 & 2
- Susheel to analyse the data in Excel to identify users who are receiving the notifications

**Comment by susheelvar** [comment]
@karntrehan to have call with Abhay and Yuvraj to discuss next steps.

@yuvrajsab to create APIs to generate user-data (phone number) from FusionAuth using the token received from PostHog and generate into single CSV data dump.

**Comment by karntrehan** [comment]
@yuvrajsab and @choxx working on this.

Posthog saving data to clickhouse. We are exploring connecting clickhouse to metabase directly.

**Comment by karntrehan** [comment]
Moving to NL project.
