### ISSUE TITLE
UCI Milestones

### ISSUE THREAD

**Issue by chinmoy12c** [samagra-comms/uci-apis#159]
These are some future milestones that we're currently looking at:

Wave 1: Adoptability & Contributability

- [x] Make UCI easier to adopt/integrate. This includes work on the DevOps side to make the setup of UCI easier. The final goal would be to run a single script and setup the entire ecosystem of UCI with all the services as well as populate seed data.
Tracked by: https://github.com/samagra-comms/docker-deploy/issues/78
Assigned to: @RyanWalker277 

- [x] Fix all the documentation and reflect the changes done to UCI. This includes the user manual for the admin console, UCI backend changes as well as REST API changes.
Tracked by: https://github.com/samagra-comms/community/issues/53
Assigned to: @chinmoy12c @geeky-abhishek 

- [ ] Add tests to solidify the behavior of all the services in notification triggering and bot communication. Each test should be independent of external services. This is required since there are a lot of expected changes in C4GT GraalVM project, and adding these tests would give confidence that changes are not breaking any usage.
Tracked by: https://github.com/samagra-comms/inbound/issues/78
Assigned to: @pankajjangid05

- [x] Documentation for Database Schema
Tracked by: https://github.com/samagra-comms/dao/issues/18
Assigned to: 

Wave 2: Stability, Scalability & Maintenenability

- [x] Optimize UCI further to support more requests per second.
Tracked by: https://github.com/samagra-comms/uci-apis/issues/160
Assigned to: @chinmoy12c 

- [ ] Fix the complete test suite of UCI-APIs.
Tracked by: #95 

- [ ] Clean up transaction layer code where bad code practices have been followed.
Tracked by: https://github.com/samagra-comms/adapter/issues/30
Assigned to: @pankajjangid05 

- [ ] Port transaction layer services to GraalVM to optimize the performance of all the services. This includes making all the services GraalVM compatible, which requires the services to be able to compile "Ahead of time".
Tracked by: #65 

Wave 3: Visualization & Security analysis

- [x] Create a complete monitoring dashboard that can view details about the system in real time and removes the dependency on engineers to keep track of the overall process. This will be handled in C4GT project.
Tracked by: https://github.com/samagra-comms/inbound/issues/42

- [ ] Security analysis of the UCI system. Currently, we have certain security vulnerabilities in our UCI system which need to be fixed to avoid leakage of sensitive data and any potential attack on our system.
Assigned to: @chinmoy12c

**Comment by karntrehan** [comment]
Lets update this ticket.
